config/routes.rb
Rails.application.routes.draw do
  root "sessions#home"

  get '/' => 'sessions#show'

  post '/' => 'sessions#create'
  
  match '/auth/:provider/callback' => 'sessions#google',  via: [:get, :post]

  get '/signup' => 'users#new'

  post '/signup' => 'users#create'

  get '/search', to: 'users#search', as: 'search'
  
  resources :sessions, only: [:create, :show, :destroy]
  resources :services
  resources :users
  resources :posts 
  resources :userfavorites, only: [:index, :create, :destroy ]
  
  resources :users do 
    resources :posts
    resources :userfavorites
  end 
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :user
    belongs_to :post 
    
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user 
    belongs_to :service
    has_many :user_favorites 
    has_many :users, through: :user_favorites 
end

app/models/service.rb
class Service < ApplicationRecord
    has_many :posts
end

app/models/user.rb
class User < ApplicationRecord
    has_many :posts
    has_many :comments
    has_many :userfavorites
    has_many :favorited_posts, through: :userfavorites, source: :post
    has_many :services, through: :posts
  
    has_secure_password 
    validates :username, :email, presence: true

    def favorite?(post)
        !!self.userfavorites.find_by(post: post)
    end 
end

app/models/userfavorite.rb
class Userfavorite < ApplicationRecord
    belongs_to :user
    belongs_to :post 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user, :logged_in?

    private 
    def current_user 
        User.find_by(id: session[:user_id])
    end 

    def logged_in?
        !!session[:user_id]
    end 

    def require_login 
        unless logged_in?
            redirect_to root_path
        end 
    end 

    def redirect_if_not_logged_in
        redirect_to '/' if !logged_in?
    end 

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :redirect_if_not_logged_in

    def index 
        render 'index'
    end 
    
    def new 
        @post = Post.new
    end 

    def create 
        @post = Post.new(post_params)
        @post.user_id = current_user.id
        if @post.save 
            flash[:success] = "Sucessfully Saved Post!"
            redirect_to user_path(current_user)
        else  
            render 'new'
        end 
    end 

    def show
        set_post
    end 

    def edit
        set_post
        redirect_to_post_path if @post.user != current_user
    end 

    def update 
        set_post 
        redirect_to_post_path if @post.user != current_user
        if @post.update(post_params)
            flash[:success] = "Updated successfully!"
            redirect_to post_path(@post)
        else 
            flash[:error] = "Unsuccessful update. Try again!"
            render :edit
        end 
    end 

    def destroy
        set_post
        if current_user == @post.user
            @post.destroy
            redirect_to user_path(current_user)
        else  
            flash[:alert] = "Sorry, you can only delete your own post"
            redirect_to @post
        end 
    end 
    
    def set_post
        @post = Post.find_by_id(params[:id])
    end 

    def post_params 
        params.require(:post).permit(:title, :content, :service_id)
    end 
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
    before_action :redirect_if_not_logged_in

    def index 
        @services = Service.paginate(page: params[:page], per_page:20)
    end 

    def show 
        redirect_if_not_logged_in
        @service = Service.find(params[:id])
    end 
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    
    def show 
        if logged_in?
          redirect_to user_path(current_user)
        else 
          redirect_to root_path
        end 
      end 

    def destroy 
        session.clear
        redirect_to root_path
      end 

    def create 
        user = User.find_by(email: params[:user][:email])
        if user && user.authenticate(params[:user][:password])
            session[:user_id] = user.id
            redirect_to user_path(user)
        else 
          redirect_to root_path
          flash[:error] = "Your credentials were invalid.  Please sign up or try again."
        end 
    end 

    def google 
      @user = User.find_or_create_by(email: auth["info"]["email"]) do |user|
        user.username = auth["info"]["first_name"]
        user.password = SecureRandom.hex(10)
      end
      if @user.save
        session[:user_id] = @user.id
        redirect_to user_path(@user)
      else
        redirect_to '/'
      end
    end

    private

    def auth
      request.env['omniauth.auth']
    end 
end

app/controllers/userfavorites_controller.rb
class UserfavoritesController < ApplicationController
    before_action :redirect_if_not_logged_in

    def create 
        user_fav = current_user.userfavorites.build(post_id: params[:format])
        if user_fav.save
            flash[:success] = "Sucessfully saved to your favorites."
            redirect_to post_path(Post.find_by_id(params[:format]))
        else
            flash[:error] = "Something went wrong when adding to your favorites."
            redirect_to current_user 
        end 
    end 

    def index
        render "index"
    end 

    def destroy
        set_userfavorites
        @userfavorites.destroy
        redirect_to post_path(Post.find_by_id(params[:id]))
        flash[:success] = "Sucessfully removed from your favorites."
    end 
    
    private 

    def set_userfavorites
        @userfavorites = Userfavorite.find_by(post_id: params[:id], user_id: current_user.id)
    end 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def index 
        render :show
    end 
    def new 
        @user = User.new
    end 

    def create 
        @user = User.new(user_params)
        if @user.save 
            session[:user_id] = @user.id 
            flash[:success] = "You have successfuly created an account! Welcome to the The Freelance Hub community!"
            redirect_to @user 
        else 
            flash[:error] = "Account creation failure: #{@user.errors.full_messages.to_sentence}"
            render :new
        end 
    end 

    def show 
        redirect_if_not_logged_in
        @user = User.find_by_id(params[:id])
        redirect to '/' if !@user 
    end 

    def user_params 
        params.require(:user).permit(:username, :email, :password)
    end 

    def search 
        if params[:search] == ""
            render "show"
        else 
            x = params[:search].downcase.strip
            @posts_results = Post.where("Lower(title) LIKE?", "%#{x}%")
        end 
    end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
    
    def display_posts
        if @user.posts.empty?
          tag.h2(link_to('No postings yet - write a post here', new_post_path))
        else
          content_tag(:h2, "Your Posts:")
        end 
    end 
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/userfavorites_helper.rb
module UserfavoritesHelper

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_messages.html.erb
<%= content_tag(:div, flash[:error], class: "text-danger text-center", :id => "flash_error") if flash[:error] %>
<%= content_tag(:div, flash[:notice], class: "text-warning text-center", :id => "flash_notice") if flash[:notice] %>
<%= content_tag(:div, flash[:alert], class: "text-danger text-center", :id => "flash_alert") if flash[:alert] %>
<%= content_tag(:div, flash[:success], class: "text-success text-center", :id => "flash_success") if flash[:success] %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-primary fw-bold">
  <div class="container-fluid">
    <a class="navbar-brand text-white fs-3" href="/users/<%=current_user.id%>">The Freelance Hub</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active text-white" aria-current="page" href= "/users/<%=current_user.id%>" >Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active text-white" href="/users/<%=current_user.id%>/posts">Your Posts</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active text-white" href="/users/<%=current_user.id%>/userfavorites">Favorites</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active text-white" href="/users/<%=current_user.id%>/posts/new">Create New Posts</a>
        </li>
        <li class="nav-item">
          <%= link_to "Logout", session_path(current_user),method: :delete, class: "nav-link active text-white" %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_submenu.html.erb
<nav class="border border-3 border-start-0 border-end-0 navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid mb-0 align-items-center text-center position-relative d-flex justify-content-center">
      <ul class="navbar-nav mb-0 mb-lg-0">
      <% Service.all.each do |service|%>
        <li class="nav-item mb-0 p-1">
          <a class="nav-link active fw-bold text-secondary" aria-current="page" href="/services/<%=service.id%>"><%=service.name%></a>
        </li>
        <%end%>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>The Freelance Hub</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
            <%= render 'layouts/navbar' if current_user %>
            <%= render 'layouts/submenu' %>
            <%= render 'layouts/messages' %>
  </head>

  <body>
        <%= yield %>
  </body>
</html>

app/views/posts/_favorite.html.erb
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.8/css/all.css" integrity="sha384-3AB7yXWz4OeoZcPbieVW64vVXEwADiYyAEhwilzWsLw+9FgqpyjjStpPnpBO8o8S" crossorigin="anonymous">
<%if current_user.favorite? (@post)%>
    <%= link_to "Remove from my favorites", userfavorite_path(@post), class:"btn btn-primary btn-rounded" , 
    method: :delete, data: {confirm: "Are you sure?"}%>
<%else%>
    <%= link_to "Add to my favorites", userfavorites_path(@post), class:"btn btn-light btn-rounded", method: :create  %>
<%end%>

app/views/posts/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10 pt-4 bg-brand-facebook rounded">
      <%= form_for(@post) do |f| %>
        <div class="form-group row medium">
          <%= f.label :title, class: "col-sm col-form-label text-black fw-bold" %>
          <div class="col-10">
            <%= f.text_field :title, class: "form-control rounded", placeholder: "Title of Post" %>
          </div>
        </div><br>

        <div class="form-group row medium">
          <%= f.label :content, class: "col-sm col-form-label text-black fw-bold" %>
          <div class="col-10"> 
            <%= f.text_area :content, rows: 8, class: "form-control", placeholder: "Tell us more" %>
          </div>
        </div><br>

        <div class="form-group row medium">
          <%= f.label :service, class: "col-sm col-form-label text-black fw-bold" %>
          <div class="col-10"> 
            <%= f.collection_select(:service_id, Service.all, :id, :name,
            { prompt: "select one of the following for the service category"}, { size: 10, class: "custom-select col-10" }) %>
          </div>
        </div><br>

        <div class="col-12 justify-content-center text-center">
          <%= f.submit class: "btn btn-block btn-primary" %>
        </div>

      <% end %>
    </div>

    <div class="col-12 justify-content-center">
    <div class="mb-3 text-center ">
        <br>
      <%= link_to '[ Cancel and return to Homepage ]', user_path(current_user), class: "text-info text-center text-black" %>
    </div>
    </div>
  </div>
</div>

app/views/posts/_posts.html.erb
<ul>
  <% posts.each do |p|%>
    <li><%= link_to p.title, post_path(p) %></li>
  <% end %>
</ul>

app/views/posts/edit.html.erb
<%=render 'form'%>

app/views/posts/index.html.erb
<div class="container  ">
  <div class="row justify-content-center">
    <div class="fw-bold, text-center m-3">
      <h2>Your Posts:</h2>
    </div>
    
        <% if current_user.posts.empty?%>
          <section class="post-list text-center">
            <h4><%="Looks like you don't have any posts yet..."%></h4>
          </section>

        <% else %>
          <% current_user.posts.each do |post| %>
            <section class="post-list mb-1"> 
              <div>
                <div class="post-list__time fw-bold text-center">
                  <%= Post.find_by_id(post).created_at.to_time.strftime('%_m/%-d/%Y') %>
                </div>
                
                <div class="post-list__preview">
                  <h4><%= link_to Post.find_by_id(post).title, post_path(Post.find_by_id(post)) %></h4>
                </div>
              </div>
            </section>
          <% end %>
        <% end %>
    </div>
</div>

app/views/posts/new.html.erb
<%=render 'form'%>

app/views/posts/show.html.erb
<div class="container">
  <div class="row col-12-lg justify-content-center rounded">
    <div class="col-md-8 mt-5">
      <div class="card col-12-lg text-center shadow mb bg-light rounded rounded">

        <div class="card-body col-12 p-3 bg-primary">
          <div class="h3 card-text text-center text-light"><%= @post.title%> 
          </div>
          <span><%= render 'favorite' %></span>
        </div>

          <div class="card-body bg-light col-12 rounded p-0 m-0">
            <h5><textarea disabled style="color:black;" rows="18" class="small card-body col-12 bg-grey rounded "><%= @post.content %></textarea></h5>
          </div>

        <div><br>
            <p class="text-dark fw-bold">Services:</p>
            <span class="badge badge-white"><%=link_to @post.service.name.upcase, "" %></span>
        <div><br>
  
        <div class="card-footer text-muted bg-primary ">
          <strong class = "text-light">Created by <%= @post.user.username %>, on <%= (@post.created_at).to_time.strftime('%B %e %Y at %l:%M %p') %> </br>
          edited <%= time_ago_in_words(@post.updated_at) %> ago</strong>
          <br>
          <br>
          <%= link_to "Edit", edit_post_path(@post), class: "btn-sm btn-light text-decoration-none" if current_user == @post.user%>
          <%= link_to "Delete", post_path(@post),
           method: :delete,
           class: "btn-sm btn-light text-decoration-none",
           data: {confirm: "Are you sure?"} if current_user == @post.user%>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/services/show.html.erb
<div class="container  ">
  <div class="row justify-content-center">
    <div class="fw-bold, text-center m-3">
      <h1><%=@service.name%></h1>
    </div>
    <section class="post-list"> 
      <% @service.posts.each do |post| %>
        <section class="post-list mb-1"> 
          <div>
            <div class="post-list__time fw-bold text-center">
              <%= post.created_at.to_time.strftime('%_m/%-d/%Y') %>
            </div>
              <div class="text-dark post-list__preview text-dark">
                <h4><%= link_to post.title, post_path(post) %></h4>
              </div>
            </div>
        </section>
      <% end %>
    </section>
  </div>
</div>

app/views/userfavorites/index.html.erb
<div class="container  ">
  <div class="row justify-content-center">
    <div class="fw-bold, text-center m-3">
      <h2>Your Favorites:</h2>
    </div>
    
        <% if current_user.userfavorites.empty?%>
          <section class="post-list text-center">
            <h4><%="Looks like you don't have any favorites yet..."%></h4>
          </section>

        <% else %>
          <% current_user.userfavorites.each do |fav| %>
            <section class="post-list mb-1"> 
              <div>
                <div class="post-list__time fw-bold text-center">
                  <%= Post.find_by_id(fav.post_id).created_at.to_time.strftime('%_m/%-d/%Y') %>
                </div>
                
                <div class="post-list__preview">
                  <h4><%= link_to Post.find_by_id(fav.post_id).title, post_path(Post.find_by_id(fav.post_id)) %></h4>
                </div>
              </div>
            </section>
          <% end %>
        <% end %>
    </div>
</div>

app/views/users/new.html.erb
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.8/css/all.css" integrity="sha384-3AB7yXWz4OeoZcPbieVW64vVXEwADiYyAEhwilzWsLw+9FgqpyjjStpPnpBO8o8S" crossorigin="anonymous">

  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-12 col-md-8 col-lg-6 col-xl-5">
        <div class="card bg-light shadow text-black border-light" style="border-radius: 1rem;">
          <div class="card-body p-5 ">
            <div class="mb-md-3 mt-md-3 pb-4">
              <h3 class ="text-left">Sign up</h3>

              <%= form_for(@user) do |f| %>   
                <div class="form-outline form-white mb-4">
                  <%= f.label :username , class: "form-control-label" %><br />
                  <%= f.text_field :username , autofocus: true, autocomplete: "username", class: "form-control form-control-prepend" %>
                </div>

                <div class="form-outline form-white mb-4">
                  <%= f.label :email , class: "form-control-label" %><br />
                  <%= f.text_field :email , autofocus: true, autocomplete: "email", class: "form-control form-control-prepend" %>
                </div>

                <div class="form-outline form-white mb-4">
                  <%= f.label "Password" , class: "form-control-label" %><br />
                  <%= f.password_field :password, autocomplete: "new-password", class: "form-control form-control-prepend" %>
                </div>

                <div class="form-outline form-white mb-4">
                  <%= f.label "Password confirmation", class: "form-control-label"%><br />
                  <%= f.password_field :password_confirmation, autocomplete: "new-password", class: "form-control form-control-prepend" %>
                </div><br>
              
                <div class="actions">
                  <%= f.submit "Sign up", class: "btn btn-block btn-primary form-control "%>
                </div><br>

              <% end %>

                <div class="actions">
                  <%=link_to "back to home page", '/', class: "btn btn-block btn-primary form-control"%>
                </div><br>         

            </div>
          </div>
        </div>
       </div>
     </div>
  </div>

app/views/users/search.html.erb
<div class="container">
    <div class="row justify-content-center">
      <div class="col-lg-9 text-center m-5">
          <form action="/search" method="get">
              <div class="form-group bg-primary rounded-pill mb-0 px-2 py-2 shadow">
                  <div class="row">
                      <div class="col">
                          <div class="input-group input-group-merge shadow-none">
                              <div class="input-group-prepend">
                                <span class="input-group-text bg-transparent border-0"><i data-feather="search"></i></span>
                              </div>
                              <input class="form-control form-control-flush shadow-none" type="text" name="search" placeholder="Search again ...">
                                <div class="col-auto">
                                 <button class="btn btn-block btn-primary rounded-pill" type="submit">Search</button>
                                </div>
                          </div>
                      </div>
                  </div>
              </div>
          </form>
      </div>
    </div>
</div>

<div class="container">
    <div class="row justify-content-center">
        <div class="fw-bold, text-center">
            <h2>Search Results: </h1><br>
        </div>
            <section class="post-list"> 
                <% @posts_results.each do |post| %>
                    <section class="post-list mb-3"> 
                        <div>
                            <div class="post-list__time fw-bold text-center">
                                <%= post.created_at.to_time.strftime('%_m/%-d/%Y') %>
                            </div>
                            <div class="post-list__preview">
                                <h4><%= link_to post.title, post_path(post) %></h4>
                                    <div class="post-show__topics">
                                        <a class ="btn btn-primary btn-sm" href="/services/<%=post.service.id%>"> <h6><%= post.service.name.upcase %></h6>
                                        </a>
                                    </div>
                            </div>
                        </div>
                    </section>
                <% end %>
           </section>
     </div>
</div>

app/views/users/show.html.erb
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.8/css/all.css" integrity="sha384-3AB7yXWz4OeoZcPbieVW64vVXEwADiYyAEhwilzWsLw+9FgqpyjjStpPnpBO8o8S" crossorigin="anonymous">

<div class="container">
    <div class="row justify-content-center">
      <div class="col-lg-9 text-center m-5">
          <form action="/search" method="get">
              <div class="form-group bg-primary rounded-pill mb-0 px-2 py-2 shadow">
                  <div class="row">
                      <div class="col">
                          <div class="input-group input-group-merge shadow-none">
                              <div class="input-group-prepend">
                                <span class="input-group-text bg-transparent border-0"><i data-feather="search"></i></span>
                              </div>
                              <input class="form-control form-control-flush shadow-none" type="text" name="search" placeholder="Search again ...">
                                <div class="col-auto">
                                 <button class="btn btn-block btn-primary rounded-pill" type="submit">Search</button>
                                </div>
                          </div>
                      </div>
                  </div>
              </div>
          </form>
      </div>
    </div>
</div>

<div class="container">
    <div class="row justify-content-center">
      <section class="post-list"> 
          <% Post.all.each do |post| %>
              <section class="post-list mb-3"> 
                  <div>
                      <div class="post-list__time fw-bold text-center">
                          <%= post.created_at.to_time.strftime('%_m/%-d/%Y') %>
                      </div>
                      <div class="post-list__preview">
                          <h4><%= link_to post.title, post_path(post) %></h4>
                              <div class="post-show__topics">
                              <a class ="btn btn-primary btn-sm" href="/services/<%=post.service.id%>"> <h6><%= post.service.name.upcase %></h6>
                              </a>
                              </div>
                      </div>
                  </div>
              </section>
          <% end %>
      </section>
    </div>
</div>